//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;

    [DataContract]

    public partial class BcciSery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BcciSery()
        {
            this.BcciSeries1 = new HashSet<BcciSery>();
        }

        [DataMember]
        public int MatchId { get; set; }

        [DataMember]
        public string MatchName { get; set; }

        [DataMember]
        public string Team1 { get; set; }

        [DataMember]
        public string Team2 { get; set; }

        [DataMember]
        public Nullable<System.DateTime> MatchDate { get; set; }

        [DataMember]
        public string Venue { get; set; }

        [DataMember]
        public Nullable<int> SeriesId { get; set; }

        [DataMember]
        public string SeriesName { get; set; }

        [DataMember]
        public Nullable<System.DateTime> SeriesStartDate { get; set; }

        [DataMember]
        public Nullable<System.DateTime> SeriesEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BcciSery> BcciSeries1 { get; set; }
        public virtual BcciSery BcciSery1 { get; set; }
    }
}
